		<ul class="to-form-field-list">
			<li>
				<h5><?php esc_html_e('Logo','bookingo'); ?></h5>
				<span class="to-legend"><?php esc_html_e('Select company logo.','bookingo'); ?></span>
				<div class="to-clear-fix">
					<input type="text" name="<?php BGCBSHelper::getFormName('logo'); ?>" id="<?php BGCBSHelper::getFormName('logo'); ?>" class="to-float-left" value="<?php echo esc_attr($this->data['option']['logo']); ?>"/>
					<input type="button" name="<?php BGCBSHelper::getFormName('logo_browse'); ?>" id="<?php BGCBSHelper::getFormName('logo_browse'); ?>" class="to-button-browse to-button" value="<?php esc_attr_e('Browse','bookingo'); ?>"/>
				</div>
			</li> 
			<li>
				<h5><?php esc_html_e('Currency','bookingo'); ?></h5>
				<span class="to-legend"><?php esc_html_e('Currency.','bookingo'); ?></span>
				<div class="to-clear-fix">
					<select name="<?php BGCBSHelper::getFormName('currency'); ?>" id="<?php BGCBSHelper::getFormName('currency'); ?>">
<?php
						foreach($this->data['dictionary']['currency'] as $index=>$value)
							echo '<option value="'.esc_attr($index).'" '.(BGCBSHelper::selectedIf($this->data['option']['currency'],$index,false)).'>'.esc_html($index.' ('.$value['name'].')').'</option>';
?>
					</select>
				</div>
			</li>
			<li>
				<h5><?php esc_html_e('Date format','bookingo'); ?></h5>
				<span class="to-legend"><?php echo sprintf(esc_html__('Select the date format to be displayed. More info you can find here %s.','bookingo'),'<a href="https://codex.wordpress.org/Formatting_Date_and_Time" target="_blank">Formatting Date and Time</a>'); ?></span>
				<div class="to-clear-fix">
					<input type="text" name="<?php BGCBSHelper::getFormName('date_format'); ?>" id="<?php BGCBSHelper::getFormName('date_format'); ?>" value="<?php echo esc_attr($this->data['option']['date_format']); ?>"/>
				</div>
			</li>  
			<li>
				<h5><?php esc_html_e('Time format','bookingo'); ?></h5>
				<span class="to-legend"><?php echo sprintf(esc_html__('Select the time format to be displayed. More info you can find here %s.','bookingo'),'<a href="https://codex.wordpress.org/Formatting_Date_and_Time" target="_blank">Formatting Date and Time</a>'); ?></span>
				<div class="to-clear-fix">
					<input type="text" name="<?php BGCBSHelper::getFormName('time_format'); ?>" id="<?php BGCBSHelper::getFormName('time_format'); ?>" value="<?php echo esc_attr($this->data['option']['time_format']); ?>"/>
				</div>
			</li>		
			<li>
				<h5><?php esc_html_e('Address format','bookingo'); ?></h5>
				<span class="to-legend"><?php esc_html_e('Determine in which way elements of the address (street name/number, city, country etc.) should be displayed.','bookingo'); ?></span>
				<div class="to-radio-button">
					<input type="radio" value="1" id="<?php BGCBSHelper::getFormName('address_format_1'); ?>" name="<?php BGCBSHelper::getFormName('address_format'); ?>" <?php BGCBSHelper::checkedIf($this->data['option']['address_format'],1); ?>/>
					<label for="<?php BGCBSHelper::getFormName('address_format_1'); ?>"><?php esc_html_e('Layout I','bookingo'); ?></label>
					<input type="radio" value="2" id="<?php BGCBSHelper::getFormName('address_format_2'); ?>" name="<?php BGCBSHelper::getFormName('address_format'); ?>" <?php BGCBSHelper::checkedIf($this->data['option']['address_format'],2); ?>/>
					<label for="<?php BGCBSHelper::getFormName('address_format_2'); ?>"><?php esc_html_e('Layout II (US)','bookingo'); ?></label>
				</div>
			</li>	
			<li>
				<h5><?php esc_html_e('Default sender e-mail account','bookingo'); ?></h5>
				<span class="to-legend">
					<?php esc_html_e('Select default e-mail account.','bookingo'); ?><br/>
					<?php esc_html_e('It will be used to sending email messages to clients about changing of booking status.','bookingo'); ?>
				</span>
				<div class="to-clear-fix">
					<select name="<?php BGCBSHelper::getFormName('sender_default_email_account_id'); ?>" id="<?php BGCBSHelper::getFormName('sender_default_email_account_id'); ?>">
<?php
						echo '<option value="-1" '.(BGCBSHelper::selectedIf($this->data['option']['sender_default_email_account_id'],-1,false)).'>'.esc_html__('- Not set -','bookingo').'</option>';
						foreach($this->data['dictionary']['email_account'] as $index=>$value)
							echo '<option value="'.esc_attr($index).'" '.(BGCBSHelper::selectedIf($this->data['option']['sender_default_email_account_id'],$index,false)).'>'.esc_html($value['post']->post_title).'</option>';
?>
					</select>
				</div>
			</li>
			<li>
				<h5><?php esc_html_e('Fixer.io API key','bookingo'); ?></h5>
				<span class="to-legend">
					<?php echo sprintf(__('Enter API key generated by <a href="%s" target="_blank">Fixer.io</a>.','bookingo'),'https://fixer.io/'); ?><br/>
				</span>
				<div class="to-clear-fix">
					<input type="text" name="<?php BGCBSHelper::getFormName('fixer_io_api_key'); ?>" id="<?php BGCBSHelper::getFormName('fixer_io_api_key'); ?>" value="<?php echo esc_attr($this->data['option']['fixer_io_api_key']); ?>"/>
				</div>
			</li>
		</ul>